version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: expense-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  pipeline:
    build: .
    container_name: expense-pipeline
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    ports:
      - "8888:8888"
    command: bash run_pipeline.sh

volumes:
  mongo_data:
